### ISSUE TITLE
Chrome libs missing in docker build

### ISSUE THREAD

**Issue by yao-yun** [coolmoon327/UESTC-QingShuiHe-SRUN-TELECOM#7]
Chrome-headless-shell-linux64 needed libs are still missing in docker. Will try to install the dependency of chromium

ref: https://stackoverflow.com/q/76730257

```
root@c688cb72635e:/home/webdriver/chrome-headless-shell-linux64# ./chrome-headless-shell
./chrome-headless-shell: error while loading shared libraries: libdbus-1.so.3: cannot open shared object file: No such file or directory
```
```
Start watching network status
Network is disconnected. Try login now.
Start trying times: 1
Traceback (most recent call last):
  File "/home/auto_login.py", line 170, in <module>
    login.start()
  File "/home/auto_login.py", line 140, in start
    self._login()  # 重新登录
  File "/home/auto_login.py", line 117, in _login
    self._login_srun()
  File "/home/auto_login.py", line 78, in _login_srun
    driver = webdriver.Chrome(service=s, options=self.options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.      
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location webdriver/chrome-headless-shell-linux64/chrome-headless-shell is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55c2ce4c6b83 <unknown>
#1 0x55c2ce187567 <unknown>
#2 0x55c2ce1be917 <unknown>
#3 0x55c2ce1bb50e <unknown>
#4 0x55c2ce20bbe0 <unknown>
#5 0x55c2ce200223 <unknown>
#6 0x55c2ce1c8144 <unknown>
#7 0x55c2ce1c954e <unknown>
#8 0x55c2ce48bc41 <unknown>
#9 0x55c2ce48fb55 <unknown>
#10 0x55c2ce478ad5 <unknown>
#11 0x55c2ce4907ef <unknown>
#12 0x55c2ce45c32f <unknown>
#13 0x55c2ce4b3da8 <unknown>
#14 0x55c2ce4b3f77 <unknown>
#15 0x55c2ce4c5d24 <unknown>
#16 0x7f39e9ed0ac3 <unknown>
```

**Comment by yao-yun** [comment]
a more convenient way is to use npm: https://developer.chrome.com/blog/chrome-for-testing/#how-can-i-get-chrome-for-testing-binaries , but that would be redundant
